### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [BlazeCodeDev/TSViewer#1]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by BlazeCodeDev** [comment]
Hi there, thanks for the suggestion. I already considered that and read the faq. I've read that the build server takes up 150gb of storage and only runs on Linux. I just need to free some storage and install a VM or is there an easier way using windows?

**Comment by x13a** [comment]
Firstly you have to add `fastlane/metadata` to your project. You can take a look [Vibe](https://github.com/x13a/Vibe) for example.

After that you have to create `Merge Request` to [F-Droid Data](https://gitlab.com/fdroid/fdroiddata/-/merge_requests). It will be `com.blazecode.tsviewer.yml` file with instructions. You can take a look [me.lucky.vibe.yml](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/me.lucky.vibe.yml) for example. Because `TS` is closed source, you have to add 
```yaml
AntiFeatures:
  - NonFreeNet
```
to your file I suppose.

**Comment by BlazeCodeDev** [comment]
Thanks! I added some of the files, I just need to verify my GitLab account.

**Comment by BlazeCodeDev** [comment]
It took a while, but here it is:

https://f-droid.org/en/packages/com.blazecode.tsviewer/
